spring:
  application:
    name: TransactionService
  cache:
    type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.105:3307/transactionservice
    username: root
    password: martinkrum
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: 192.168.0.105
      port: 6380
      password: alicepassword
      username: alice
  kafka:
    bootstrap-servers: 192.168.0.105:9092
server:
  port: 8080